"""Regression suite for ``public/reproduce_tandem_tbox_db.py`` -- the single-file,
from-``Master_tboxes.csv`` reproduction of the tbdb.tandem dataset.

The point of this suite is to prove the refactor preserved reproduction: every
pipeline run is diffed, byte-for-byte, against the committed golden baseline in
``tests/golden/`` (the Phase-0 oracle, generated by the pre-refactor script).

LOCAL-ONLY by design. The full pipeline reads the 92 MB ``Master_tboxes.csv``,
which is never committed (see ``data-pipeline/README.md``). CI's ``data`` job has
no copy, so the pipeline-dependent tests SKIP there; they run locally where the
source CSV is on disk -- auto-discovered next to the repo, or point
``TBOX_MASTER_CSV`` at it. The golden-integrity check needs no CSV and always runs.

REPRODUCIBILITY CAVEAT. The byte-for-byte guarantee is BioPython-version-
sensitive: ``PairwiseAligner.align(a, b)[0]`` returns the FIRST of possibly
several co-optimal global alignments, and gap placement shifts the identity
denominator -- so a different BioPython can change ``identity.json`` /
``summary.json`` bytes. The golden baseline is validated under the versions
pinned in ``tests/requirements.txt`` (``biopython==1.87``, ``pandas==3.0.3``);
when those pins move, run this suite and regenerate ``tests/golden/`` only if
the byte-for-byte check changes.
``test_determinism`` re-documents this.
"""
from __future__ import annotations

import hashlib
import importlib.util
import json
import math
import os
from pathlib import Path

import pytest

# --- locations -------------------------------------------------------------
REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPT_PATH = REPO_ROOT / "public" / "reproduce_tandem_tbox_db.py"
GOLDEN_DIR = Path(__file__).resolve().parent / "golden"
OUTPUT_FILES = (
    "loci.json", "members.json", "identity.json", "summary.json",
    "members.csv", "tree_input.fasta", "antiterm_fallback.fasta", "tandem_loci.tsv",
)


def _load_reproduce_module():
    """Import the downloadable script (it lives under ``public/``, not on sys.path)."""
    spec = importlib.util.spec_from_file_location("reproduce_tandem_tbox_db", SCRIPT_PATH)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


repro = _load_reproduce_module()


def _find_master() -> Path | None:
    """Locate the read-only source CSV without committing its 92 MB.

    Honours ``TBOX_MASTER_CSV`` first; otherwise walks up from the repo looking
    for a sibling ``tboxdb-master/Master_tboxes.csv`` (or the tboxevo mirror) --
    which resolves from both a normal checkout and a nested git worktree.
    """
    override = os.environ.get("TBOX_MASTER_CSV")
    if override and Path(override).is_file():
        return Path(override)
    rels = (
        ("tboxdb-master", "Master_tboxes.csv"),
        ("tboxevo", "data", "raw", "Master_tboxes.csv"),
    )
    for base in (REPO_ROOT, *REPO_ROOT.parents):
        for rel in rels:
            candidate = base.joinpath(*rel)
            if candidate.is_file():
                return candidate
    return None


MASTER = _find_master()
needs_master = pytest.mark.skipif(
    MASTER is None,
    reason="Master_tboxes.csv not found (set TBOX_MASTER_CSV); the reproduction "
           "tests are local-only -- CI has no 92 MB source CSV",
)


# --- helpers ---------------------------------------------------------------
def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _golden_shas() -> dict:
    shas = {}
    for line in (GOLDEN_DIR / "SHA256SUMS").read_text().splitlines():
        line = line.strip()
        if line:
            sha, name = line.split(maxsplit=1)
            shas[name.strip()] = sha
    return shas


def _run_pipeline(out_dir: Path, *extra_args) -> Path:
    rc = repro.main(["--master", str(MASTER), "--out", str(out_dir), "--emit-table", *extra_args])
    assert rc == 0
    return out_dir


def _load_objects(out_dir: Path):
    loci = json.loads((out_dir / "loci.json").read_text())["loci"]
    members = json.loads((out_dir / "members.json").read_text())
    pairs = json.loads((out_dir / "identity.json").read_text())
    return loci, members, pairs


# --- fixtures (session-scoped: each pipeline run loads the 92 MB CSV, ~25 s) ---
@pytest.fixture(scope="session")
def run_default(tmp_path_factory) -> Path:
    """One default-mode pipeline run (Phase-2 fix on, --emit-table)."""
    return _run_pipeline(tmp_path_factory.mktemp("default"))


@pytest.fixture(scope="session")
def run_default_again(tmp_path_factory) -> Path:
    """A second, independent default-mode run -- for the determinism check."""
    return _run_pipeline(tmp_path_factory.mktemp("default2"))


@pytest.fixture(scope="session")
def run_legacy(tmp_path_factory) -> Path:
    """A run with --legacy-empty-structure (the pre-fix str(NaN)->'...' behavior)."""
    return _run_pipeline(tmp_path_factory.mktemp("legacy"), "--legacy-empty-structure")


# --- tests -----------------------------------------------------------------
def test_golden_baseline_intact():
    """The committed golden files still match their SHA256SUMS (no CSV needed)."""
    shas = _golden_shas()
    assert set(shas) == set(OUTPUT_FILES), "SHA256SUMS does not list exactly the 8 outputs"
    corrupted = [n for n in OUTPUT_FILES if _sha256(GOLDEN_DIR / n) != shas[n]]
    assert not corrupted, f"golden file(s) corrupted: {corrupted}"


@needs_master
def test_phase1_byte_identical(run_default):
    """Every regenerated output is byte-for-byte equal to the golden baseline.

    This is the regression gate for the entire Phase-1 refactor (and, since the
    Phase-2 fix is latent on the published source, for Phase 2 too): zero diffs.
    """
    shas = _golden_shas()
    mismatched = [n for n in OUTPUT_FILES if _sha256(run_default / n) != shas[n]]
    assert not mismatched, f"outputs differ from golden: {mismatched}"


@needs_master
def test_invariants(run_default):
    """Structural invariants that hold for any valid run (dataset-agnostic)."""
    loci, members, pairs = _load_objects(run_default)
    repro.verify_invariants(loci, members, pairs)  # raises SystemExit on violation

    assert len(pairs) == sum(math.comb(o["n_cores"], 2) for o in loci)
    assert sum(o["n_cores"] for o in loci) == len(members)
    for mid, m in members.items():
        struct = m["structure"]
        if struct is not None:
            assert repro.is_balanced(struct), f"{mid}: Stem-I structure unbalanced"
        a, b = m["coords"]["leader"]
        assert len(m["fasta_sequence"]) == abs(b - a) + 1, f"{mid}: fasta != leader span"
        assert m["tbdb_url"] or m["ncbi_url"], f"{mid}: resolves to no URL"


@needs_master
def test_golden_counts(run_default):
    """The published magic numbers, via verify_golden + explicit assertions."""
    loci, members, pairs = _load_objects(run_default)
    repro.verify_golden(loci, members, pairs)  # raises SystemExit on violation

    assert len(loci) == 470
    assert len(members) == 949
    assert len(pairs) == 488
    high = sum(1 for o in loci if o["confidence"] == "high")
    low = sum(1 for o in loci if o["confidence"] == "low")
    assert (high, low) == (394, 76)
    cp = next(o for o in loci if o["accession"] == "CP045927")
    assert [members[mid]["specifier"]["aa"] for mid in cp["member_ids"]] == ["TRP", "VAL"]


@needs_master
def test_determinism(run_default, run_default_again):
    """Two independent runs are byte-identical.

    Guards JSON key ordering, dict-iteration order, and the
    ``PairwiseAligner.align(...)[0]`` co-optimal tie-break. NB: the *absolute*
    bytes are BioPython-version-dependent (see module docstring + requirements.txt);
    this asserts run-to-run stability within one environment, not cross-version
    equality. The BioPython version is recorded below for triage.
    """
    import Bio
    assert isinstance(Bio.__version__, str)
    differing = [
        n for n in OUTPUT_FILES
        if _sha256(run_default / n) != _sha256(run_default_again / n)
    ]
    assert not differing, f"nondeterministic outputs: {differing}"


# --- Phase 2: the structure null-guard ------------------------------------
def test_phase2_fix_nulls_missing_structure():
    """The default null-guard maps a missing source Structure to None, not "...".

    No CSV needed -- exercises the Phase-2 helper directly. This is what *proves*
    the fix is correct, since the full-dataset diff (below) is empty: no selected
    member on the published source has a missing Structure.
    """
    # The latent bug the guard prevents: NaN -> "nan" -> a balanced, fake "...".
    assert repro.wuss_to_dotbracket(str(float("nan"))) == "..."
    # Default mode null-guards; legacy mode reproduces the bug; present values match.
    assert repro._member_structure(float("nan"), legacy=False) is None
    assert repro._member_structure(float("nan"), legacy=True) == "..."
    assert repro._member_structure("   ", legacy=False) is None
    assert repro._member_structure("<<<...>>>", legacy=False) == "(((...)))"
    assert repro._member_structure("<<<...>>>", legacy=True) == "(((...)))"


@needs_master
def test_phase2_legacy_reproduces_golden(run_legacy):
    """--legacy-empty-structure reproduces the published bytes exactly.

    The golden baseline was captured from the pre-fix script, so legacy mode is
    its exact source of truth -- a robust anchor even if a future source makes
    the fix non-trivial.
    """
    shas = _golden_shas()
    mismatched = [n for n in OUTPUT_FILES if _sha256(run_legacy / n) != shas[n]]
    assert not mismatched, f"legacy mode differs from golden: {mismatched}"


@needs_master
def test_phase2_bounded_diff(run_default):
    """The Phase-2 fix (default) changes members.json ONLY by flipping
    ``structure`` from "..." to null on members whose source Structure is missing;
    the seven other outputs stay byte-identical to golden, and no other key on any
    member changes. The affected-member count is reported so the diff is auditable.
    """
    shas = _golden_shas()
    for name in OUTPUT_FILES:
        if name != "members.json":
            assert _sha256(run_default / name) == shas[name], f"{name} unexpectedly changed"

    golden_members = json.loads((GOLDEN_DIR / "members.json").read_text())
    new_members = json.loads((run_default / "members.json").read_text())
    assert set(golden_members) == set(new_members), "member_id set changed"

    changed = [mid for mid in golden_members if golden_members[mid] != new_members[mid]]
    for mid in changed:
        old, new = dict(golden_members[mid]), dict(new_members[mid])
        assert old.pop("structure") == "...", f"{mid}: changed member's golden structure was not '...'"
        assert new.pop("structure") is None, f"{mid}: new structure is not null"
        assert old == new, f"{mid}: a key other than `structure` changed"

    print(f"\nPhase-2 affected members: {len(changed)} {sorted(changed)}")
    # On the published source the affected set is empty (the lone missing-Structure
    # row is not a selected member) -- so members.json is also byte-identical.
    if not changed:
        assert _sha256(run_default / "members.json") == shas["members.json"]


# ===========================================================================
# The optional --genomic-context engine (ported from the maintainer module).
# Pure, no network: dependency-injected fixture fetchers + a faithfulness
# cross-check against data-pipeline/fetch_genomic_context.py. These run in CI
# (no Master needed) and guard that the self-contained port did not drift.
# ===========================================================================
import fetch_genomic_context as fc  # noqa: E402 - the maintainer module the script ports from
import ncbi_ids  # noqa: E402


def _gbxml(coded_by: str) -> str:
    return (
        "<GBSet><GBSeq><GBSeq_feature-table><GBFeature>"
        "<GBFeature_key>CDS</GBFeature_key><GBFeature_quals><GBQualifier>"
        f"<GBQualifier_name>coded_by</GBQualifier_name><GBQualifier_value>{coded_by}</GBQualifier_value>"
        "</GBQualifier></GBFeature_quals></GBFeature></GBSeq_feature-table></GBSeq></GBSet>"
    )


def _plus_fixture():
    plus = ("ACGT" * 15)[:60]  # genomic (+)-strand interval [101..160]
    locus = {"tandem_id": "TT01", "accession": "ACC1", "strand": "+",
             "downstream_id": "gb|PROT1.1|", "downstream_gene": "geneX"}
    members = [
        {"member_id": "TT01.m1", "ordinal": 1, "coords": {"leader": [101, 120]}, "fasta_sequence": plus[0:20]},
        {"member_id": "TT01.m2", "ordinal": 2, "coords": {"leader": [131, 150]}, "fasta_sequence": plus[30:50]},
    ]
    return locus, members, {"PROT1.1": _gbxml("ACC1.1:155..160")}, f">ACC1.1:101-160\n{plus}\n"


def _minus_fixture():
    plus = ("GGTTCAAC" * 8)[:60]  # locus on the MINUS strand
    locus = {"tandem_id": "TT02", "accession": "ACC2", "strand": "-",
             "downstream_id": "gb|PROT2.1|", "downstream_gene": "geneY"}
    members = [
        {"member_id": "TT02.m1", "ordinal": 1, "coords": {"leader": [260, 241]},
         "fasta_sequence": fc.revcomp(plus[40:60])},
        {"member_id": "TT02.m2", "ordinal": 2, "coords": {"leader": [240, 221]},
         "fasta_sequence": fc.revcomp(plus[20:40])},
    ]
    return locus, members, {"PROT2.1": _gbxml("complement(ACC2.1:201..210)")}, f">ACC2.1:201-260\n{plus}\n"


@pytest.mark.parametrize("fixture", [_plus_fixture, _minus_fixture])
def test_ported_genomic_engine_matches_maintainer_module(fixture):
    """The script's PORTED build_locus_record is byte-faithful to the maintainer module
    data-pipeline/fetch_genomic_context.py for identical inputs, on BOTH strands -- the
    output dicts carry plain values, so ``==`` compares the full assembly cleanly."""
    locus, members, proteins, fasta = fixture()
    fp = lambda pid: proteins.get(pid)        # noqa: E731
    fi = lambda acc, lo, hi: fasta            # noqa: E731
    assert repro.build_locus_record(locus, members, fp, fi) == fc.build_locus_record(locus, members, fp, fi)


def test_ported_parsers_match_maintainer_module():
    """The ported pure parsers equal the maintainer module's, value-for-value (the immutable
    holders differ -- namedtuple here vs dataclass there -- so compare field values)."""
    dids = "gb|OLE31895.1||gnl|WGS:MNJJ|AUG45_11735;dbj|BAM48243.1|"
    assert ([(g.raw, g.protein_id, g.locus_tag) for g in repro.parse_downstream_id(dids)]
            == [(g.raw, g.protein_id, g.locus_tag) for g in ncbi_ids.parse_downstream_id(dids)])
    for cb in ("ACC1.1:155..160", "complement(ACC2.1:201..210)", "join(A:1..3,A:7..9)", "", "junk"):
        a, b = repro.parse_coded_by(cb), fc.parse_coded_by(cb)
        assert (a is None) == (b is None)
        if a is not None:
            assert (a.accession, a.start, a.end, a.strand) == (b.accession, b.start, b.end, b.strand)
    assert repro.extract_coded_by(_gbxml("X:1..6")) == fc.extract_coded_by(_gbxml("X:1..6"))
    assert repro.parse_fasta_seq(">h\nacgt\nTTT\n") == fc.parse_fasta_seq(">h\nacgt\nTTT\n")


def test_genomic_columns_fill_from_context(tmp_path):
    """write_members_csv fills the genomic columns from a context map: the proximal
    co-oriented gene + the inverse-offset genomic span, the per-element offset, the
    interval, the resolved flag, and the operon-size count."""
    locus, members, proteins, fasta = _plus_fixture()
    rec = repro.build_locus_record(locus, members, lambda pid: proteins.get(pid),
                                   lambda a, lo, hi: fasta)
    locus_obj = {"tandem_id": "TT01", "accession": "ACC1", "strand": "+", "organism": None,
                 "phylum": None, "member_ids": ["TT01.m1", "TT01.m2"]}
    mmap = {m["member_id"]: {"member_id": m["member_id"], "tandem_id": "TT01",
                             "ordinal": m["ordinal"], "fasta_sequence": m["fasta_sequence"],
                             "coords": {"leader": m["coords"]["leader"], "window": {}},
                             "stems": [], "specifier": {}, "downstream": {}}
            for m in members}
    repro.write_members_csv([locus_obj], mmap, tmp_path, context_by_locus={"TT01": rec})
    import csv
    rows = list(csv.reader((tmp_path / "members.csv").open()))
    idx = {c: i for i, c in enumerate(rows[0])}
    r1 = rows[1]  # TT01.m1, the most-5' element (offset 0)
    assert r1[idx["genomic_resolved"]] == "true"
    assert (r1[idx["locus_interval_start"]], r1[idx["locus_interval_end"]]) == ("101", "160")
    assert r1[idx["element_offset"]] == "0"
    assert r1[idx["downstream_gene_id"]] == "PROT1.1"
    assert r1[idx["downstream_gene_strand"]] == "+"
    # gene genomic [155..160] recovered from offset 54 + length 6 over interval [101..160]
    assert (r1[idx["downstream_gene_start"]], r1[idx["downstream_gene_end"]]) == ("155", "160")
    assert r1[idx["downstream_gene_count"]] == "1"
    # without a context map every genomic cell is blank (additive columns)
    repro.write_members_csv([locus_obj], mmap, tmp_path)  # no context_by_locus
    blank = list(csv.reader((tmp_path / "members.csv").open()))[1]
    assert all(blank[idx[c]] == "" for c in repro._GENOMIC_CSV_COLS)


def test_genomic_fetch_no_credential_leak(tmp_path):
    """Secret hygiene: an offline NcbiClient touches no network, holds no Entrez handle, and
    neither a cache path nor a built locus_context record ever carries the email / API key."""
    client = repro.NcbiClient(tmp_path / "cache", email="secret@example.org",
                              api_key="SECRETKEY123", offline=True)
    assert not hasattr(client, "_entrez")           # offline -> biopython never imported/bound
    assert client.fetch_protein("PROT1.1") is None   # cache miss + offline -> None, no network
    assert client.fetch_interval("ACC1", 1, 60) is None
    for root, _dirs, files in os.walk(tmp_path):
        for name in files:
            assert "SECRETKEY123" not in name and "secret@example.org" not in name
    locus, members, proteins, fasta = _plus_fixture()
    rec = repro.build_locus_record(locus, members, lambda pid: proteins.get(pid),
                                   lambda a, lo, hi: fasta)
    blob = json.dumps(rec)
    assert "SECRETKEY123" not in blob and "secret@example.org" not in blob


def test_genomic_context_cli_validation(tmp_path, monkeypatch):
    """--genomic-context / --locus-context are mutually exclusive, and --genomic-context
    without --offline requires an email -- both fail fast (before any source CSV is read)."""
    monkeypatch.delenv("NCBI_EMAIL", raising=False)
    monkeypatch.delenv("NCBI_API_KEY", raising=False)
    unread = str(tmp_path / "never_read.csv")  # validation fires before load_master
    with pytest.raises(SystemExit):
        repro.main(["--master", unread, "--out", str(tmp_path),
                    "--genomic-context", "--locus-context", str(tmp_path)])
    with pytest.raises(SystemExit):
        repro.main(["--master", unread, "--out", str(tmp_path), "--genomic-context"])  # no email


def test_golden_members_csv_genomic_columns_blank():
    """The golden members.csv (a default, network-free run) carries the 12 genomic columns
    in its header, all blank -- proving the columns are additive and only fill via
    --genomic-context / --locus-context."""
    import csv
    rows = list(csv.reader((GOLDEN_DIR / "members.csv").open(newline="")))
    header = rows[0]
    assert header == repro._MEMBER_CSV_HEADER
    assert set(repro._GENOMIC_CSV_COLS) <= set(header)
    gi = [header.index(c) for c in repro._GENOMIC_CSV_COLS]
    assert all(r[i] == "" for r in rows[1:] for i in gi)
