"""Regression suite for ``public/reproduce_tandem_tbox_db.py`` -- the single-file,
from-``Master_tboxes.csv`` reproduction of the tbdb.tandem dataset.

The point of this suite is to prove the refactor preserved reproduction: every
pipeline run is diffed, byte-for-byte, against the committed golden baseline in
``tests/golden/`` (the Phase-0 oracle, generated by the pre-refactor script).

LOCAL-ONLY by design. The full pipeline reads the 92 MB ``Master_tboxes.csv``,
which is never committed (see ``data-pipeline/README.md``). CI's ``data`` job has
no copy, so the pipeline-dependent tests SKIP there; they run locally where the
source CSV is on disk -- auto-discovered next to the repo, or point
``TBOX_MASTER_CSV`` at it. The golden-integrity check needs no CSV and always runs.

REPRODUCIBILITY CAVEAT. The byte-for-byte guarantee is BioPython-version-
sensitive: ``PairwiseAligner.align(a, b)[0]`` returns the FIRST of possibly
several co-optimal global alignments, and gap placement shifts the identity
denominator -- so a different BioPython can change ``identity.json`` /
``summary.json`` bytes. The golden baseline was built with the versions pinned in
``tests/requirements.txt`` (``biopython==1.85``, ``pandas==3.0.0``).
``test_determinism`` re-documents this.
"""
from __future__ import annotations

import hashlib
import importlib.util
import json
import math
import os
from pathlib import Path

import pytest

# --- locations -------------------------------------------------------------
REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPT_PATH = REPO_ROOT / "public" / "reproduce_tandem_tbox_db.py"
GOLDEN_DIR = Path(__file__).resolve().parent / "golden"
OUTPUT_FILES = (
    "loci.json", "members.json", "identity.json", "summary.json",
    "members.csv", "tree_input.fasta", "antiterm_fallback.fasta", "tandem_loci.tsv",
)


def _load_reproduce_module():
    """Import the downloadable script (it lives under ``public/``, not on sys.path)."""
    spec = importlib.util.spec_from_file_location("reproduce_tandem_tbox_db", SCRIPT_PATH)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


repro = _load_reproduce_module()


def _find_master() -> Path | None:
    """Locate the read-only source CSV without committing its 92 MB.

    Honours ``TBOX_MASTER_CSV`` first; otherwise walks up from the repo looking
    for a sibling ``tboxdb-master/Master_tboxes.csv`` (or the tboxevo mirror) --
    which resolves from both a normal checkout and a nested git worktree.
    """
    override = os.environ.get("TBOX_MASTER_CSV")
    if override and Path(override).is_file():
        return Path(override)
    rels = (
        ("tboxdb-master", "Master_tboxes.csv"),
        ("tboxevo", "data", "raw", "Master_tboxes.csv"),
    )
    for base in (REPO_ROOT, *REPO_ROOT.parents):
        for rel in rels:
            candidate = base.joinpath(*rel)
            if candidate.is_file():
                return candidate
    return None


MASTER = _find_master()
needs_master = pytest.mark.skipif(
    MASTER is None,
    reason="Master_tboxes.csv not found (set TBOX_MASTER_CSV); the reproduction "
           "tests are local-only -- CI has no 92 MB source CSV",
)


# --- helpers ---------------------------------------------------------------
def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _golden_shas() -> dict:
    shas = {}
    for line in (GOLDEN_DIR / "SHA256SUMS").read_text().splitlines():
        line = line.strip()
        if line:
            sha, name = line.split(maxsplit=1)
            shas[name.strip()] = sha
    return shas


def _run_pipeline(out_dir: Path, *extra_args) -> Path:
    rc = repro.main(["--master", str(MASTER), "--out", str(out_dir), "--emit-table", *extra_args])
    assert rc == 0
    return out_dir


def _load_objects(out_dir: Path):
    loci = json.loads((out_dir / "loci.json").read_text())["loci"]
    members = json.loads((out_dir / "members.json").read_text())
    pairs = json.loads((out_dir / "identity.json").read_text())
    return loci, members, pairs


# --- fixtures (session-scoped: each pipeline run loads the 92 MB CSV, ~25 s) ---
@pytest.fixture(scope="session")
def run_default(tmp_path_factory) -> Path:
    """One default-mode pipeline run (Phase-2 fix on, --emit-table)."""
    return _run_pipeline(tmp_path_factory.mktemp("default"))


@pytest.fixture(scope="session")
def run_default_again(tmp_path_factory) -> Path:
    """A second, independent default-mode run -- for the determinism check."""
    return _run_pipeline(tmp_path_factory.mktemp("default2"))


# --- tests -----------------------------------------------------------------
def test_golden_baseline_intact():
    """The committed golden files still match their SHA256SUMS (no CSV needed)."""
    shas = _golden_shas()
    assert set(shas) == set(OUTPUT_FILES), "SHA256SUMS does not list exactly the 8 outputs"
    corrupted = [n for n in OUTPUT_FILES if _sha256(GOLDEN_DIR / n) != shas[n]]
    assert not corrupted, f"golden file(s) corrupted: {corrupted}"


@needs_master
def test_phase1_byte_identical(run_default):
    """Every regenerated output is byte-for-byte equal to the golden baseline.

    This is the regression gate for the entire Phase-1 refactor (and, since the
    Phase-2 fix is latent on the published source, for Phase 2 too): zero diffs.
    """
    shas = _golden_shas()
    mismatched = [n for n in OUTPUT_FILES if _sha256(run_default / n) != shas[n]]
    assert not mismatched, f"outputs differ from golden: {mismatched}"


@needs_master
def test_invariants(run_default):
    """Structural invariants that hold for any valid run (dataset-agnostic)."""
    loci, members, pairs = _load_objects(run_default)
    repro.verify_invariants(loci, members, pairs)  # raises SystemExit on violation

    assert len(pairs) == sum(math.comb(o["n_cores"], 2) for o in loci)
    assert sum(o["n_cores"] for o in loci) == len(members)
    for mid, m in members.items():
        struct = m["structure"]
        if struct is not None:
            assert repro.is_balanced(struct), f"{mid}: Stem-I structure unbalanced"
        a, b = m["coords"]["leader"]
        assert len(m["fasta_sequence"]) == abs(b - a) + 1, f"{mid}: fasta != leader span"
        assert m["tbdb_url"] or m["ncbi_url"], f"{mid}: resolves to no URL"


@needs_master
def test_golden_counts(run_default):
    """The published magic numbers, via verify_golden + explicit assertions."""
    loci, members, pairs = _load_objects(run_default)
    repro.verify_golden(loci, members, pairs)  # raises SystemExit on violation

    assert len(loci) == 470
    assert len(members) == 949
    assert len(pairs) == 488
    high = sum(1 for o in loci if o["confidence"] == "high")
    low = sum(1 for o in loci if o["confidence"] == "low")
    assert (high, low) == (394, 76)
    cp = next(o for o in loci if o["accession"] == "CP045927")
    assert [members[mid]["specifier"]["aa"] for mid in cp["member_ids"]] == ["TRP", "VAL"]


@needs_master
def test_determinism(run_default, run_default_again):
    """Two independent runs are byte-identical.

    Guards JSON key ordering, dict-iteration order, and the
    ``PairwiseAligner.align(...)[0]`` co-optimal tie-break. NB: the *absolute*
    bytes are BioPython-version-dependent (see module docstring + requirements.txt);
    this asserts run-to-run stability within one environment, not cross-version
    equality. The BioPython version is recorded below for triage.
    """
    import Bio
    assert isinstance(Bio.__version__, str)
    differing = [
        n for n in OUTPUT_FILES
        if _sha256(run_default / n) != _sha256(run_default_again / n)
    ]
    assert not differing, f"nondeterministic outputs: {differing}"
